### ISSUE TITLE
Bot Control Enhancement 

### ISSUE THREAD

**Issue by Kenzzer** [Pelipoika/TF2-Bot-Control#17]
This issue shows my current progression on my next pull request.
### Bomb mechanics
- [X] Fix wrong bomb upgrade for giant player bot.
- [X] Don't let the bomb carrier upgrade in spawn.
- [x] Try a new way to make bomb deploy animation visible for the deployer.
- [x] Try to backport the bomb carrier effect upon restoring a controlled bot `TF2_RestoreBot(int iClient)`.
### Controlled bot
- [X] Make the `CTFBotSquad::ShouldSquadLeaderWaitForFormation` detour slightly more efficient.
- [x] Fix the controlled bot eye glow particle effect following you.
- [x] Display annotation/instruction to players bot(for each classes) see issue #12 
### Clean-up
- [X] Fix DHook for `CCaptureFlag::PickUp` function.
- [x] Remove `CTFBotMedicHeal::SelectPatient` signature and detour as it's no longer required since PR #16 
- [x] Find linux signatures for `CTFBotSquad::ShouldSquadLeaderWaitForFormation` and `CTFBotSquad::GetLeader`

**Comment by Pelipoika** [comment]
Try a new way to make bomb deploy animation visible for the deployer.

**PlaySpecificSequence** just sends the _PlayerAnimEvent_ tempent with _m_iEvent_ as _PLAYERANIMEVENT_CUSTOM_SEQUENCE_  and valves code doesn't by default always add the player to the recipients list so a hook on PlayerAnim and just writing the nearest client to the recipients would propably fix it
