### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by caxanga334** [Pelipoika/TF2-Bot-Control#29]
I would like to try using this instead of be with robots but I only have Linux servers.
Do you have plans for adding support to Linux?

**Comment by Pelipoika** [comment]
Should already work on linux if you compiled the extension for linux

**Comment by caxanga334** [comment]
Well I don't know how to compile an extension.

**Comment by Pelipoika** [comment]
What's your steam account

**Comment by caxanga334** [comment]
https://steamcommunity.com/profiles/76561198053992136/

**Comment by Pelipoika** [comment]
Thanks, https://docs.google.com/document/d/1RkiqeDje5uOReer9Ja5CFaB-ZVQgKDByXAVc8taPKyc/edit

**Comment by Pelipoika** [comment]
Benoist compiled a linux binary for you https://github.com/Pelipoika/TF2-Bot-Control/tree/master/sourcemod/extensions
